name: Deploy Snapshots

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: central
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD

    - name: Deploy snapshot
      run: mvn -B deploy --file pom.xml
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Trigger build of config-pihsl
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GHA_WRITE_TOKEN }}
        repository: PIH/openmrs-config-pihsl
        event-type: dependency-trigger

    - name: Trigger build of config-zl
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GHA_WRITE_TOKEN }}
        repository: PIH/openmrs-config-zl
        event-type: dependency-trigger

    - name: Trigger build of config-pihliberia
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GHA_WRITE_TOKEN }}
        repository: PIH/openmrs-config-pihliberia
        event-type: dependency-trigger

    - name: Trigger build of config-ces
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GHA_WRITE_TOKEN }}
        repository: PIH/openmrs-config-ces
        event-type: dependency-trigger



